- name: Include vars of vars.yaml
  include_vars: vars.yaml

- name: Create a lock file used by containers for exclusive lock 
  ansible.builtin.file:
    path: /var/lock/bluetooth.lock
    state: touch
    owner: root
    group: root
    mode: '0755'

- name: Print collector List
  debug:
    msg: "Found app: {{ item.name }}"
  loop: "{{ collectors }}"

- name: Copy Dockerfile and app files
  synchronize:
    src: "{{ path }}/"
    dest: /tmp/appDockerfiles
    delete: yes
    recursive: yes
  notify:
    - Build appCollector image

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers

- name: Find MAC addresses
  script: "{{ path }}/scripts/get-mac-adress.sh {{ item.device }}" 
  register: deviceResults
  loop: "{{ collectors }}"

- include_tasks: run_containers_to_mqtt.yaml
  loop: "{{ deviceResults.results }}"
  loop_control:
    loop_var: outer_item
  when: telemetryToMqtt and not telemetryToIoTHub

- include_tasks: run_containers_to_IoTHub.yaml
  loop: "{{ deviceResults.results }}"
  loop_control:
    loop_var: outer_item
  when: not telemetryToMqtt and telemetryToIoTHub
  
- include_tasks: run_containers_to_mqtt_IoTHub.yaml
  loop: "{{ deviceResults.results }}"
  loop_control:
    loop_var: outer_item
  when: telemetryToMqtt and telemetryToIoTHub
