---
- hosts: all
  become_user: root
  become: yes
  roles:
    - role: installDocker
      tags: installDocker

- hosts: mqttHost
  become_user: root
  become: yes
  roles:
  - role: runMQTT
    tags: runMQTT

- hosts: devices
  become_user: root
  become: yes
  roles:
  - role: runCollectors
    vars:
       path: "{{ playbook_dir }}/../appCollector/"
    tags: runCollectors

