name: publish
on:
  push:
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      
      - name: Build theDocker image
        run: docker buildx build --platform linux/arm/v7 ./appCollector/ --tag ghcr.io/john-ltf/collector-armv7:1.0
        
      - name: Push the Docker image
        run: docker push ghcr.io/john-ltf/collector-armv7:1.0
