name: publish
on:
  push:
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      
      - name: Build the hello-docker Docker image
        run: docker build ./appCollector/Dockerfile --tag ghcr.io/john-ltf/collector:1.0
        
      - name: Push the hello-docker Docker image
        run: docker push ghcr.io/John-ltf/collector:1.0
