name: publish
on:
  push:
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: dump
        run: |
          echo 'github.workspace === ${{ github.workspace }}'
          echo "GITHUB_WORKSPACE === $GITHUB_WORKSPACE"
          echo 'runner.workspace === ${{ runner.workspace }}'
          echo "RUNNER_WORKSPACE === $RUNNER_WORKSPACE"
          echo "$(pwd)"
          
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      
      - name: Build the hello-docker Docker image
        run: docker build ${{ runner.workspace }}/appCollector/Dockerfile --tag ghcr.io/john-ltf/collector:1.0
        
      - name: Push the hello-docker Docker image
        run: docker push ghcr.io/John-ltf/collector:1.0
